services:
  interface:
    image: ghcr.io/rxsio/robot-web-interface:nightly
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    environment:
      - 'true'
    volumes:
      - '/certificates:/certificates'
      - '/rover/configuration:/configuration'
      - '/rover/exchange:/exchange'
  cameras:
    image: ghcr.io/rxsio/webrtc-camera-server:nightly
    restart: unless-stopped
    ports:
      - 8443:8443
    environment:
      - 'true'
    privileged: true
    volumes:
      - '/run/udev:/run/udev:ro'
      - '/dev:/dev'
      - '/certificates:/certificates'
      - '/rover/configuration:/configuration'
      - '/rover/exchange:/exchange'
  ros:
    image: ghcr.io/rxsio/firo_robot:humble
    restart: unless-stopped
    network_mode: host
    ipc: host
    privileged: true # This is intentional
    command: 'ros2 launch firo_bringup firo_bringup.launch '
    volumes:
      - '/certificates:/certificates'
      - '/rover/configuration:/configuration'
      - '/rover/exchange:/exchange'
    devices:
      - '/dev:/dev'
