providers:
  docker:
    exposedByDefault: false
  file:
    filename: /traefik_dynamic.yaml
entryPoints:
  web:
    address: :80
    # http:
    #   redirections:
    #     entrypoint:
    #       to: websecure
    #       scheme: https
  websecure:
    address: :443
    asDefault:
      true
      tls: {}
serversTransport:
  rootCAs:
    filename: /certificates/RootCA.pem