providers:
  docker:
    exposedByDefault: false
entryPoints:
  web:
    address: :80
    http:
      redirections:
        entrypoint:
          to: websecure
          scheme: https
  websecure:
    address: :443
    asDefault: true
    http:
      tls:
        certResolver: le
api:
  dashboard: true
certificatesResolvers:
  le:
    acme:
      email: firo2@rxsio.com
      storage: /acme.json
      caServer: https://acme-staging-v02.api.letsencrypt.org/directory
      dnsChallenge:
        provider: cloudflare